apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: k9kdttiq4-nodejs 
  janus-idp.io/tekton: k9kdttiq4-nodejs
  backstage.io/kubernetes-id: k9kdttiq4-nodejs
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: k9kdttiq4-nodejs
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml